### ISSUE TITLE
Cannot transfer funds

### ISSUE THREAD

**Issue by crappyrules** [kegcoin-project/kegcoin-gold#11]
For some weird reason, I cannot seem to transfer any of my kegcoin funds to the exchange.  I believe that there is something awry and I am concerned that as an unregistered ICO speculative investors may be concerned and forced to file reports with the regulatory commissions in their legal jurisdictions.

**Comment by twgobble** [comment]
have you tried turning it off and on again

**Comment by LeoCornelius** [comment]
The ICO was cancelled
